language: node_js
node_js:
- '8'
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  local-dir: www
  fqdn: today.pihkala.info
  on:
    branch: master
env:
  global:
    secure: UOvVuIZBDFENYwxi1hsh5WepicULWrW1fkoDss66/FYVmX/gEIqsutMNk8VApyINkhzpg+FAWK8MFOBQwISpcjNX9dleN2AqGgI6EhGBS4BnO+jJjR/+tzGqqI+RPZBawUfCVzZAytuC1i1NuIdu5yyJCAhjJMrF10MAGFdueyG2RRYvBXHQjmlJa27/oxMtd12ks5DyB90Xz9pfqsyNrBiTC/qR14ih8B8zFifXAwi0qOFoi0DbK90vJXC3CJeqbgsbLDhE5wpyiQ/+zacsGPlig6BeeXfrI4Hqhp2MEgr8cEF4i/PsOqnS+t9lO4orOHR6lh64ujKJM+wf20kTPA68xH8gn0tHoUTlnVN4hRqY4COeI+Dh4WX87Te6r7yFTc/bOfvBfgj2ugfMiefwxGe/067jfieubJ1llKiftO0WB3OqSyiP1hYOmkIzS/62qKDcGSzIAVxdQHER6DVExWZtPEeY0/u8CAZWY8bwyJDw6NNe7O9Mc/o3g/4rUI5oaBwMgfe4na4vN8yuT5Uhb6wn0B9GeUYsDmwUSjBjVPRlpBHr5OXpkLUox3ecMKvQavwPDjTaGEHOuTAB8cc72XcmdiDPYRVqLdEeRX7iZGPRG3UiuzmzprOiUs4eMFvq0hlGY6n0tSrrXcY+QFX86TEwCe2FJp8HqYerot9w8fA=
